var m1 = Array(5)
console.log(m1)
console.log(typeof(m1))
let m2 = new Array(10,34,75)
console.log(m2)
let m3 = ["Hello","Welcome"]
console.log(m3)
console.log(m3.length)
m1.push(10)
console.log(m1.length)
m2.pop()
console.log(m2)
m1.pop()
console.log(m1)
m1.pop()
console.log(m1)
console.log(m1.length)
console.log(m2.indexOf(10))
console.log(m2.includes(5))
console.log(m2.includes(34))